"""adicionar cpf em paciente

Revision ID: 445bbeebaa4f
Revises: 
Create Date: 2026-04-22 23:40:34.884093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445bbeebaa4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'consulta', 'medico', ['idMedico'], ['idMedico'])
    op.create_foreign_key(None, 'consulta', 'local', ['idLocal'], ['idLocal'])
    op.create_foreign_key(None, 'consulta', 'paciente', ['idPaciente'], ['idPaciente'])
    op.add_column('paciente', sa.Column('cpf', sa.String(length=14), nullable=True))
    op.create_unique_constraint(None, 'paciente', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paciente', type_='unique')
    op.drop_column('paciente', 'cpf')
    op.drop_constraint(None, 'consulta', type_='foreignkey')
    op.drop_constraint(None, 'consulta', type_='foreignkey')
    op.drop_constraint(None, 'consulta', type_='foreignkey')
    # ### end Alembic commands ###
