"""adicionar dataNascimento em paciente

Revision ID: 47e74a42cc08
Revises: 445bbeebaa4f
Create Date: 2026-04-24 20:37:12.280908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e74a42cc08'
down_revision: Union[str, Sequence[str], None] = '445bbeebaa4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paciente', sa.Column('dataNascimento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paciente', 'dataNascimento')
    # ### end Alembic commands ###
