"""adicionar telegramChatId em paciente

Revision ID: 555b3b0ad696
Revises: 47e74a42cc08
Create Date: 2026-05-07 21:37:33.393948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '555b3b0ad696'
down_revision: Union[str, Sequence[str], None] = '47e74a42cc08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paciente', sa.Column('telegramChatId', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paciente', 'telegramChatId')
    # ### end Alembic commands ###
